'use client';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from 'react';

import { ThemeProvider } from 'next-themes';
import { ThemeSwitcher } from '@/components/ThemeSwitcher';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body>
//         <ThemeProvider attribute="class">
//           <div className="min-h-screen p-4">
//             <header className="mb-4 flex justify-between items-center">
//               <h1 className="text-2xl font-bold">Quiz App</h1>
//               <ThemeSwitcher />
//             </header>
//             {children}
//           </div>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }


export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return <>{children}</>;
  }

  return (
    <html lang="en" suppressHydrationWarning>
        
      <body>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <div className="min-h-screen p-4">
         <header className="mb-4 flex justify-between items-center">
        <h1 className="text-2xl font-bold">Quiz App</h1>
           <ThemeSwitcher />
         </header>
          {children}
       </div>
       </ThemeProvider>
      </body>
     
    </html>
  );
}